import React from 'react';
import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { Header } from '@/header';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="de">
            <body className={`h-screen bg-gradient-to-r from-background-brown to-neutral-50`}>
                <div className="bg-red-400 h-16 flex flex-col content-center">
                    <Header />
                </div>
                {children}
            </body>
        </html>
    );
}
